version: "3.9"

services:
  web:
    build: .
    command: python3 ./djangoreactfw/manage.py runserver 0.0.0.0:8000 
    ports:
      - "80:8000"
    depends_on:
      - redis

  redis:
    image: redis:5.0.8-alpine
    ports:
      - "6379:6379"