version: "3.9"

services:
  web:
    build: .
    command: sh -c "cd djangoreactfw/reactfend && npm run dev & 
                    python3 djangoreactfw/manage.py makemigrations &&
                    python3 djangoreactfw/manage.py migrate &&
                    python3 djangoreactfw/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app/
    ports:
      - "80:8000"
    env_file:
      - ./.env
    depends_on:
      - redis
      - postgresdb

  postgresdb:
    image: postgres:14-alpine
    env_file:
      - ./.env
    container_name: postgresdb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}  

  redis:
    image: redis:5.0.8-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:    