# Generated by Django 4.0.2 on 2022-02-23 16:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('provisoryapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoroom',
            name='num',
        ),
        migrations.AddField(
            model_name='videoroom',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
