# Generated by Django 4.0.2 on 2022-06-29 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('provisoryapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoroom',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videorooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
