# Generated by Django 4.0.2 on 2022-03-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisoryapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoroom',
            name='videopath',
            field=models.TextField(default='Path goes here!'),
        ),
    ]
