# Generated by Django 4.0.2 on 2022-04-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisoryapi', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoroom',
            name='videopath',
            field=models.FileField(upload_to='content/%Y/%m/%d'),
        ),
    ]
